# Explore here

In [1]:
import pandas as pd
import numpy as np
import ast

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import make_regression
from sklearn.datasets import load_wine

from sklearn.model_selection import train_test_split

# supervisado
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# no supervisado
from sklearn.neighbors import NearestNeighbors

from sklearn.metrics import accuracy_score

from sklearn.metrics import mean_squared_error, r2_score

import warnings
warnings.filterwarnings('ignore')

from pickle import dump

In [2]:
movies= pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_movies.csv")
credits= pd.read_csv("https://raw.githubusercontent.com/4GeeksAcademy/k-nearest-neighbors-project-tutorial/main/tmdb_5000_credits.csv")

movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [3]:
credits

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4798,9367,El Mariachi,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [4]:
# Renombramos la columna "id" en movies a "movie_id" para que coincidan
movies.rename(columns={"id": "movie_id"}, inplace=True)

# Realizamos el merge usando la columna "movie_id"
merged_df = pd.merge(movies, credits, on="movie_id", how="inner")

# Mostramos los primeros registros del DataFrame unificado
merged_df.columns
merged_df.head()

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
# Seleccionar las columnas especÃ­ficas con .loc
df = merged_df.loc[:, ['movie_id', 'title_x',"title_y", 'overview', 'genres', 'keywords', 'cast', 'crew']]


# Verificar si las columnas "title_x" y "title_y" tienen los mismos datos
print(df['title_x'].equals(df['title_y']))
#si sin iguales devuelve true

True

In [7]:
# Eliminamos una de las columnas y renombramos a "title" la otra
df=df.drop("title_y",axis=1)
df.rename(columns={"title_x": "title"}, inplace=True)
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [8]:
# FunciÃ³n para extraer la lista de 'name' de un JSON y reemplazar la columna
def extract_names(json_str):
    try:
        # Convierte la cadena en un objeto de Python
        json_obj = ast.literal_eval(json_str)
        # Extrae el atributo 'name' de cada diccionario
        return ', '.join([item['name'] for item in json_obj])  # Combina los gÃ©neros como una cadena
    except (ValueError, SyntaxError):
        return ''

# FunciÃ³n para obtener los tres primeros nombres del reparto
def extract_top_cast(json_str):
    try:
        json_obj = ast.literal_eval(json_str)
        return ', '.join([item['name'] for item in json_obj[:3]])  # Combina los tres nombres como una cadena
    except (ValueError, SyntaxError):
        return ''

In [11]:
# Transformar y reemplazar las columnas
df['genres'] = df['genres'].apply(extract_names)  # Reemplaza 'genres' por los nombres de los gÃ©neros
df['keywords'] = df['keywords'].apply(extract_names)  # Reemplaza 'keywords' por los nombres de las palabras clave
df['cast'] = df['cast'].apply(extract_top_cast)  # Reemplaza 'cast' por los tres primeros nombres del reparto
df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...",,,,James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...",,,,Gore Verbinski
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...",,,,Sam Mendes
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...",,,,Christopher Nolan
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...",,,,Andrew Stanton

In [10]:
# FunciÃ³n para obtener el nombre del director de la columna 'crew'
def get_director(json_str):
    try:
        json_obj = ast.literal_eval(json_str)  # Convierte el string JSON en un objeto Python
        for item in json_obj:
            if item['job'] == 'Director':  # Busca el director en el equipo
                return item['name']  # Devuelve el nombre del director
        return None  # Si no se encuentra un director
    except (ValueError, SyntaxError):
        return None

# FunciÃ³n para convertir 'overview' (resumen) en una lista de palabras
def convert_overview_to_list(text):
    try:
        return text.split()  # Convierte el texto en una lista de palabras
    except AttributeError:  # Maneja valores nulos o no vÃ¡lidos
        return []

# Procesar la columna 'crew' para que solo contenga el nombre del director
df['crew'] = df['crew'].apply(get_director)

# Procesar la columna 'overview' para convertirla en una lista de palabras
df['overview'] = df['overview'].apply(convert_overview_to_list)

df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","Action, Adventure, Fantasy, Science Fiction","culture clash, future, space war, space colony...","Sam Worthington, Zoe Saldana, Sigourney Weaver",James Cameron
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","Adventure, Fantasy, Action","ocean, drug abuse, exotic island, east india t...","Johnny Depp, Orlando Bloom, Keira Knightley",Gore Verbinski
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","Action, Adventure, Crime","spy, based on novel, secret agent, sequel, mi6...","Daniel Craig, Christoph Waltz, LÃ©a Seydoux",Sam Mendes
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","Action, Crime, Drama, Thriller","dc comics, crime fighter, terrorist, secret id...","Christian Bale, Michael Caine, Gary Oldman",Christopher Nolan
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","Action, Adventure, Science Fiction","based on novel, mars, medallion, space travel,...","Taylor Kitsch, Lynn Collins, Samantha Morton",Andrew Stanton

In [12]:
# FunciÃ³n para quitar los espacios en los elementos de una lista o cadenas de texto
def remove_spaces(value):
    if isinstance(value, list):  # Si el valor es una lista
        return [item.replace(' ', '') for item in value]  # Elimina los espacios de cada elemento
    elif isinstance(value, str):  # Si el valor es una cadena de texto
        return value.replace(' ', '')  # Elimina los espacios
    else:
        return value  # Devuelve el valor sin cambios si es otro tipo

# Aplicar la funciÃ³n a las columnas correspondientes
df['genres'] = df['genres'].apply(remove_spaces)
df['cast'] = df['cast'].apply(remove_spaces)
df['crew'] = df['crew'].apply(remove_spaces)
df['keywords'] = df['keywords'].apply(remove_spaces)

In [13]:
# FunciÃ³n para limpiar espacios y comillas extras
def clean_string(value):
    # Eliminar espacios extras y comillas no deseadas
    return ' '.join(str(value).replace("'", "").split())

# FunciÃ³n para combinar todas las columnas en una sola cadena
def combine_columns(row):
    # Limpiar y combinar los valores de todas las columnas
    return ' '.join([
        clean_string(row['overview']),
        clean_string(row['genres']),
        clean_string(row['keywords']),
        clean_string(row['cast']),
        clean_string(row['crew'])
    ])

# Crear la nueva columna 'tags' combinando las columnas procesadas
df['tags'] = df.apply(combine_columns, axis=1)

# Reemplazar comas por espacios en blanco en la columna 'tags'
df['tags'] = df['tags'].str.replace(',', '')

# Mostrar el primer valor de la columna 'tags' para verificar
df["tags"][0]

'[In the 22nd century a paraplegic Marine is dispatched to the moon Pandora on a unique mission but becomes torn between following orders and protecting an alien civilization.]    JamesCameron'

In [14]:
df["tags"] = df["tags"].str.strip().str.lower()
df['tags'] = df['tags'].str.replace(" ", "")

vectorizer = TfidfVectorizer()
df_vectorized = vectorizer.fit_transform(df["tags"])
print(df_vectorized)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30495 stored elements and shape (4803, 24844)>
  Coords	Values
  (0, 11402)	0.7648827952233109
  (0, 12015)	0.6441694727099185
  (1, 5558)	0.6075387726007122
  (1, 5116)	0.6075387726007122
  (1, 9413)	0.5116573849497729
  (2, 455)	0.5192253422567832
  (2, 18996)	0.5192253422567832
  (2, 23965)	0.5192253422567832
  (2, 17726)	0.43728152473547177
  (3, 8653)	0.32433212091533403
  (3, 6981)	0.32433212091533403
  (3, 6478)	0.32433212091533403
  (3, 3588)	0.32433212091533403
  (3, 17182)	0.32433212091533403
  (3, 7708)	0.32433212091533403
  (3, 9423)	0.30936120731238675
  (3, 8507)	0.30936120731238675
  (3, 20105)	0.32433212091533403
  (3, 5925)	0.2687973478633541
  (4, 12328)	0.3680013648022795
  (4, 23172)	0.3680013648022795
  (4, 24104)	0.21505982368761795
  (4, 11186)	0.3680013648022795
  (4, 13920)	0.3680013648022795
  (4, 2179)	0.3680013648022795
  :	:
  (4800, 13702)	0.408248290463863
  (4800, 20408)	0.408248290463863
  (4800, 17905)	0.408248290463863
  (4801, 6158)	0.32230569258218594
  (4801, 24634)	0.3112392066174543
  (4801, 23359)	0.33790302852260845
  (4801, 24442)	0.33790302852260845
  (4801, 6259)	0.33790302852260845
  (4801, 21787)	0.33790302852260845
  (4801, 18712)	0.33790302852260845
  (4801, 10935)	0.33790302852260845
  (4801, 6616)	0.33790302852260845
  (4802, 10235)	0.2902275510184249
  (4802, 18429)	0.1719430565918552
  (4802, 24670)	0.15799930471043483
  (4802, 20839)	0.19992839690302774
  (4802, 8035)	0.3020795351011795
  (4802, 20187)	0.3020795351011795
  (4802, 15196)	0.3020795351011795
  (4802, 6920)	0.3020795351011795
  (4802, 15726)	0.3020795351011795
  (4802, 7449)	0.3020795351011795
  (4802, 23207)	0.3020795351011795
  (4802, 15408)	0.3020795351011795
  (4802, 4751)	0.3020795351011795

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(df_vectorized)

In [16]:
model = NearestNeighbors(n_neighbors = 6, metric = "cosine")
model.fit(df_vectorized)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [17]:
def recommend(movie):
    movie_index = df[df["title"] == movie].index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse = True , key = lambda x: x[1])[1:6]
    
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [19]:
recommend("Avatar")

True Lies
Terminator 2: Judgment Day
The Abyss
Aliens
The Terminator

In [20]:
def recommend(movie):
    # Convertir los tÃ­tulos a minÃºsculas para comparaciÃ³n insensible a mayÃºsculas
    movie = movie.lower()
    df['title_lower'] = df['title'].str.lower()  # Crear una columna auxiliar en minÃºsculas
    
    # Verificar si la pelÃ­cula existe en el DataFrame
    if movie not in df['title_lower'].values:
        print("PelÃ­cula no encontrada. Por favor, verifica el tÃ­tulo.")
        return

    # Obtener el Ã­ndice de la pelÃ­cula consultada
    movie_index = df[df["title_lower"] == movie].index[0]

    # Calcular distancias de similitud
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    # Mostrar recomendaciones
    print(f"PelÃ­culas similares a '{df.iloc[movie_index].title}':")
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [21]:
recommend("avatar")

PelÃ­culas similares a 'Avatar':
True Lies
Terminator 2: Judgment Day
The Abyss
Aliens
The Terminator